/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e303a",
        "tertiary-container": "#cc4204",
        "status-pending": "#F59E0B",
        "outline": "#727687",
        "surface-muted": "#F8FAFC",
        "inverse-on-surface": "#eff0fd",
        "secondary": "#006c49",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c2c6d8",
        "background": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "surface-bright": "#faf8ff",
        "on-error-container": "#93000a",
        "surface-dim": "#d8d9e6",
        "on-primary-fixed": "#001849",
        "surface": "#faf8ff",
        "on-secondary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-container": "#f8f7ff",
        "inverse-primary": "#b3c5ff",
        "on-tertiary-container": "#fff6f4",
        "secondary-fixed": "#6ffbbe",
        "surface-container-highest": "#e1e2ee",
        "on-surface-variant": "#424656",
        "primary": "#0050cb",
        "on-tertiary-fixed-variant": "#832600",
        "on-secondary-container": "#00714d",
        "tertiary": "#a33200",
        "tertiary-fixed-dim": "#ffb59d",
        "error": "#ba1a1a",
        "surface-variant": "#e1e2ee",
        "warm-yellow": "#FBBF24",
        "tertiary-fixed": "#ffdbd0",
        "on-tertiary-fixed": "#390c00",
        "primary-fixed": "#dae1ff",
        "on-surface": "#191b24",
        "surface-container-high": "#e6e7f4",
        "on-primary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#ecedfa",
        "on-background": "#191b24",
        "secondary-container": "#6cf8bb",
        "on-secondary-fixed-variant": "#005236",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003fa4",
        "status-unpaid": "#EF4444",
        "primary-container": "#0066ff",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#0054d6"
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
      }
    },
  },
  plugins: [],
}